# Generated by Django 3.2.8 on 2021-10-09 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('build_description', models.JSONField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'AVAILABLE')], default=0)),
                ('fields', models.JSONField()),
                ('cached_preview', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PricingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'RUB')], default=0)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.dataset')),
            ],
        ),
    ]
