# Generated by Django 3.2.8 on 2021-10-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_datasetpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpermissions',
            name='dataset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perms', to='stock.dataset'),
        ),
        migrations.AlterField(
            model_name='pricingdataset',
            name='dataset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='stock.dataset'),
        ),
    ]
