# Generated by Django 3.2.8 on 2021-10-09 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0005_alter_dataset_build_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpermissions',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricingdataset',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
