# Generated by Django 3.2.8 on 2021-10-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20211009_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='cached_preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
