version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DBNAME: lemur
      POSTGRES_USER: lemur
      POSTGRES_PASSWORD: lemur
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
