# Generated by Django 3.2.8 on 2021-10-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'MATH'), (1, 'STRINGS')])),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'COMMON'), (1, 'FILTER'), (2, 'FEATURE'), (3, 'JOIN')])),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('in_ports', models.JSONField(null=True)),
                ('out_ports', models.JSONField(blank=True)),
            ],
        ),
    ]
