# Generated by Django 3.2.8 on 2021-10-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schemablock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemablock',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Математика'), (1, 'Строки')]),
        ),
    ]
