# Generated by Django 3.2.8 on 2021-10-09 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchases',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'DONE'), (2, 'ERROR')], default=0),
        ),
        migrations.AddField(
            model_name='userpurchases',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
