# Generated by Django 3.2.8 on 2021-10-09 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('filtering', models.JSONField()),
                ('aggregation', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Workpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dataset', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'FINISHED')], default=0)),
                ('new_features', models.JSONField()),
                ('aggregation', models.JSONField()),
                ('limits', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parental_datasets', models.ManyToManyField(to='stock.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='WorkpiecePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'RUB')], default=0)),
                ('workpiece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant.workpiece')),
            ],
        ),
        migrations.CreateModel(
            name='DataSamplingUnionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parental_column_name', models.CharField(max_length=255)),
                ('child_column_name', models.CharField(max_length=255)),
                ('join_type', models.PositiveSmallIntegerField(choices=[(0, 'INNER'), (1, 'LEFT'), (2, 'RIGHT')], default=0)),
                ('child_data_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_sample', to='plant.datasampling')),
                ('parental_data_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parental_sample', to='plant.datasampling')),
                ('workpiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.workpiece')),
            ],
        ),
        migrations.AddField(
            model_name='datasampling',
            name='workpiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.workpiece'),
        ),
    ]
