# Generated by Django 3.2.8 on 2021-10-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20211009_0953'),
        ('plant', '0002_auto_20211009_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasampling',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasampling',
            name='raw_aggregation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasampling',
            name='raw_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasampling',
            name='raw_filtering',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasampling',
            name='aggregation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasampling',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasamples', to='stock.dataset'),
        ),
        migrations.AlterField(
            model_name='datasampling',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasampling',
            name='filtering',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasampling',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datasampling',
            name='workpiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasamples', to='plant.workpiece'),
        ),
    ]
