# Generated by Django 3.2.8 on 2021-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_auto_20211009_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpiece',
            name='filtering',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpiece',
            name='raw_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workpiece',
            name='raw_filtering',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
