# Generated by Django 3.2.8 on 2021-10-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_rename_filtering_workpiece_joins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpiece',
            old_name='raw_features',
            new_name='raw_joins',
        ),
    ]
