# Generated by Django 3.2.8 on 2021-10-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_remove_workpiece_raw_filtering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpiecepricing',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workpiecepricing',
            name='workpiece',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='plant.workpiece'),
        ),
    ]
