# Generated by Django 3.2.8 on 2021-10-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_auto_20211009_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasampling',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
